name: Execute Migration Script

on:
  issue_comment:
    types: [created]

jobs:
  issueops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests

      - name: Check for /run-reclaim command
        id: check-command
        run: |
          if echo "${{ github.event.comment.body }}" | grep -q "/run-reclaim"; then
            echo "Reclaim command found in the comment"
          else
            echo "No reclaim command found, skipping job."
            exit 0
          fi

      - name: Extract parameters from comment
        id: extract-params
        run: |
          EMU_USERS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--emu-users-file=")[^"]+')
          USER_MAPPINGS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--user-mappings-file=")[^"]+')
          ORG_NAME=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--org-name=")[^"]+')

          echo "EMU_USERS_FILE: $EMU_USERS_FILE"
          echo "USER_MAPPINGS_FILE: $USER_MAPPINGS_FILE"
          echo "ORG_NAME: $ORG_NAME"

          echo "EMU_USERS_FILE=$EMU_USERS_FILE" >> $GITHUB_ENV
          echo "USER_MAPPINGS_FILE=$USER_MAPPINGS_FILE" >> $GITHUB_ENV
          echo "ORG_NAME=$ORG_NAME" >> $GITHUB_ENV

      - name: Run migration script
        run: |
          echo "Running migration script with the following variables:"
          echo "EMU_USERS_FILE: $EMU_USERS_FILE"
          echo "USER_MAPPINGS_FILE: $USER_MAPPINGS_FILE"
          echo "ORG_NAME: $ORG_NAME"
          python mapping.py
