name: Execute Migration Script

on:
  issue_comment:
    types: [created]

jobs:
  issueops:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # Step 4: Check if comment contains '/run-reclaim'
      - name: Check for /run-reclaim command
        id: check-command
        run: |
          if [[ "${{ github.event.comment.body }}" == *"/run-reclaim"* ]]; then
            echo "Reclaim command found in the comment"
          else
            echo "No reclaim command found, skipping job."
            exit 0  # Exit early if no reclaim command
          fi

      # Step 5: Extract parameters from the issue comment
      - name: Extract parameters from comment
        id: extract-params
        run: |
          EMU_USERS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--emu-users-file=)[^ ]+' | tr -d '"')
          USER_MAPPINGS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--user-mappings-file=)[^ ]+' | tr -d '"')
          ORG_NAME=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--org-name=)[^ ]+')

          # Print values to debug
          echo "EMU_USERS_FILE: $EMU_USERS_FILE"
          echo "USER_MAPPINGS_FILE: $USER_MAPPINGS_FILE"
          echo "ORG_NAME: $ORG_NAME"

          # Set environment variables for further use
          echo "EMU_USERS_FILE=$EMU_USERS_FILE" >> $GITHUB_ENV
          echo "USER_MAPPINGS_FILE=$USER_MAPPINGS_FILE" >> $GITHUB_ENV
          echo "ORG_NAME=$ORG_NAME" >> $GITHUB_ENV

      # Step 6: Run the migration script
      - name: Run migration script
        run: |
          echo "Running migration script with the following variables:"
          echo "EMU_USERS_FILE: $EMU_USERS_FILE"
          echo "USER_MAPPINGS_FILE: $USER_MAPPINGS_FILE"
          echo "ORG_NAME: $ORG_NAME"
          python mapping.py
