jobs:
  issueops:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Extract parameters from the issue comment
      - name: Extract parameters from comment
        id: extract-params
        run: |
          # Extract the file names and org name from the comment
          EMU_USERS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--emu-users-file=)[^ ]+' | tr -d '"')
          USER_MAPPINGS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--user-mappings-file=)[^ ]+' | tr -d '"')
          ORG_NAME=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--org-name=)[^ ]+')

          # Print values to debug
          echo "EMU_USERS_FILE: $EMU_USERS_FILE"
          echo "USER_MAPPINGS_FILE: $USER_MAPPINGS_FILE"
          echo "ORG_NAME: $ORG_NAME"

          # Set environment variables for further use
          echo "EMU_USERS_FILE=$EMU_USERS_FILE" >> $GITHUB_ENV
          echo "USER_MAPPINGS_FILE=$USER_MAPPINGS_FILE" >> $GITHUB_ENV
          echo "ORG_NAME=$ORG_NAME" >> $GITHUB_ENV

      # Run Python script
      - name: Run migration script
        run: |
          python mapping.py
