name: IssueOps - Execute Migration Script

on:
  issue_comment:
    types: [created]

jobs:
  run-script:
    if: ${{ startsWith(github.event.comment.body, '/run-migration') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Extract parameters from comment
        id: extract-params
        run: |
          echo "EMU_USERS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--emu-users-file=)[^ ]+')" >> $GITHUB_ENV
          echo "USER_MAPPINGS_FILE=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--user-mappings-file=)[^ ]+')" >> $GITHUB_ENV
          echo "ORG_NAME=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--org-name=)[^ ]+')" >> $GITHUB_ENV

      - name: Execute Migration Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMU_USERS_FILE: ${{ env.EMU_USERS_FILE }}
          USER_MAPPINGS_FILE: ${{ env.USER_MAPPINGS_FILE }}
          ORG_NAME: ${{ env.ORG_NAME }}
        run: python mapping.py
